[package]
name = "life-wasm"
version = "0.1.0"
authors = ["Romain Clement <r.clement88@gmail.com>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.2"

[profile.release]
opt-level = "s"
